### ISSUE TITLE
Cloud you add a feature to show the brief images of top 10 models

### ISSUE THREAD

**Issue by tycholiu** [omniinfer/sd-webui-cloud-inference#15]
So we can easily choose which model to use

**Comment by AnyISalIn** [comment]
Good idea, let me think about how to implement it.

**Comment by pplabstest** [comment]
I just find this: https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper

**Comment by AnyISalIn** [comment]
> I just find this: https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper

Thanks a lot.

**Comment by AnyISalIn** [comment]
@dorothydoris  Greetings! We're excited to announce the addition of a complete model browser feature. This enhancement allows you to swiftly select models through thumbnails. Check it out at this link: [Stable Diffusion WebUI Cloud Inference Tutorial](https://github.com/omniinfer/sd-webui-cloud-inference/wiki/Stable-Diffusion-WebUI-Cloud-Inference-Tutorial#10-advanced---model-browser).
