### ISSUE TITLE
bug duration in the cloud interface checkpoint

### ISSUE THREAD

**Issue by vorstcavry** [omniinfer/sd-webui-cloud-inference#43]
![image](https://github.com/omniinfer/sd-webui-cloud-inference/assets/110011280/00a06b48-dfe4-4eb4-8d39-fc49992776f5)
 my stable diffusion has a bug in the cloud interface checkpoint, 

I have run everything according to the instructions given but instead it has an error, is there anything that can help?

**Comment by AnyISalIn** [comment]
Hi, Which version of the stable diffusion web UI are you using?

**Comment by vorstcavry** [comment]
> Hi, Which version of the stable diffusion web UI are you using?

I'm using the latest version of stable diffusion
