### ISSUE TITLE
error after running stable diffusion launch.py

### ISSUE THREAD

**Issue by vorstcavry** [omniinfer/sd-webui-cloud-inference#44]
I found an error after running stable diffusion launch.py, and this resulted in the controlnet extension not being able to be used as intended at all.

![image](https://github.com/omniinfer/sd-webui-cloud-inference/assets/110011280/482ae581-deb4-4c17-9968-6091d9bca355)

[cloud-inference] hijack failed: extensions.sd-webui-controlnet.scripts.global_state.update_cn_models
*** Error executing callback app_started_callback for /content/vorst-cavry/extensions/sd-webui-cloud-inference/scripts/main_ui.py

    Traceback (most recent call last):
      File "/content/vorst-cavry/modules/script_callbacks.py", line 139, in app_started_callback
        c.callback(demo, app)
      File "/content/vorst-cavry/extensions/sd-webui-cloud-inference/scripts/hijack.py", line 58, in hijack_on_app_started
        self._hijack_update_cn_models() # update once
      File "/content/vorst-cavry/extensions/sd-webui-cloud-inference/scripts/hijack.py", line 130, in _hijack_update_cn_models
        self.hijack_map['extensions.sd-webui-controlnet.scripts.global_state.update_cn_models']['old']()
    KeyError: 'extensions.sd-webui-controlnet.scripts.global_state.update_cn_models'`

**Comment by AnyISalIn** [comment]
Hi, which version of ControlNet are you using? In my environment, ControlNet v1.1.411 is working fine with these extensions.

**Comment by vorstcavry** [comment]
> Hi, which version of ControlNet are you using? In my environment, ControlNet v1.1.411 is working fine with these extensions.

![image](https://github.com/omniinfer/sd-webui-cloud-inference/assets/110011280/f93fec92-43be-4f47-8822-2018c396e951)

**Comment by vorstcavry** [comment]
I'm using the latest controlnet version

**Comment by AnyISalIn** [comment]
@vorstcavry, could you please provide additional logs? It's possible that some extensions are causing the issue to not work.

**Comment by vorstcavry** [comment]
`Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Version: 1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Installing clip
Installing open_clip
Installing requirements for CodeFormer
Installing requirements
loading WD14-tagger reqs from /content/vorst-cavry/extensions/tagger/requirements.txt
Checking WD14-tagger requirements.
Installing sd-webui-controlnet requirement: mediapipe
Installing sd-webui-controlnet requirement: svglib
Installing sd-webui-controlnet requirement: fvcore
Collecting ultralytics>=8.0.198
  Downloading ultralytics-8.0.201-py3-none-any.whl (644 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 644.7/644.7 kB 6.9 MB/s eta 0:00:00
Requirement already satisfied: matplotlib>=3.3.0 in /usr/local/lib/python3.10/dist-packages (from ultralytics>=8.0.198) (3.7.1)
Requirement already satisfied: numpy>=1.22.2 in /usr/local/lib/python3.10/dist-packages (from ultralytics>=8.0.198) (1.23.5)
Requirement already satisfied: opencv-python>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from ultralytics>=8.0.198) (4.8.0.76)
Requirement already satisfied: pillow>=7.1.2 in /usr/local/lib/python3.10/dist-packages (from ultralytics>=8.0.198) (9.5.0)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.10/dist-packages (from ultralytics>=8.0.198) (6.0.1)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.10/dist-packages (from ultralytics>=8.0.198) (2.31.0)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.10/dist-packages (from ultralytics>=8.0.198) (1.11.3)
Requirement already satisfied: torch>=1.8.0 in /usr/local/lib/python3.10/dist-packages (from ultralytics>=8.0.198) (2.0.1+cu118)
Requirement already satisfied: torchvision>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from ultralytics>=8.0.198) (0.15.2+cu118)
Requirement already satisfied: tqdm>=4.64.0 in /usr/local/lib/python3.10/dist-packages (from ultralytics>=8.0.198) (4.66.1)
Requirement already satisfied: pandas>=1.1.4 in /usr/local/lib/python3.10/dist-packages (from ultralytics>=8.0.198) (1.5.3)
Requirement already satisfied: seaborn>=0.11.0 in /usr/local/lib/python3.10/dist-packages (from ultralytics>=8.0.198) (0.12.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from ultralytics>=8.0.198) (5.9.5)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.10/dist-packages (from ultralytics>=8.0.198) (9.0.0)
Collecting thop>=0.1.1 (from ultralytics>=8.0.198)
  Downloading thop-0.1.1.post2209072238-py3-none-any.whl (15 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.3.0->ultralytics>=8.0.198) (1.1.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.3.0->ultralytics>=8.0.198) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.3.0->ultralytics>=8.0.198) (4.43.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.3.0->ultralytics>=8.0.198) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.3.0->ultralytics>=8.0.198) (23.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.3.0->ultralytics>=8.0.198) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.3.0->ultralytics>=8.0.198) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.4->ultralytics>=8.0.198) (2023.3.post1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.23.0->ultralytics>=8.0.198) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.23.0->ultralytics>=8.0.198) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.23.0->ultralytics>=8.0.198) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.23.0->ultralytics>=8.0.198) (2023.7.22)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.0->ultralytics>=8.0.198) (3.12.4)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.0->ultralytics>=8.0.198) (4.5.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.0->ultralytics>=8.0.198) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.0->ultralytics>=8.0.198) (3.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.0->ultralytics>=8.0.198) (3.1.2)
Requirement already satisfied: triton==2.0.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.0->ultralytics>=8.0.198) (2.0.0)
Requirement already satisfied: cmake in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch>=1.8.0->ultralytics>=8.0.198) (3.27.7)
Requirement already satisfied: lit in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch>=1.8.0->ultralytics>=8.0.198) (17.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics>=8.0.198) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.8.0->ultralytics>=8.0.198) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.8.0->ultralytics>=8.0.198) (1.3.0)
Installing collected packages: thop, ultralytics
Successfully installed thop-0.1.1.post2209072238 ultralytics-8.0.201
Installing pycloudflared
Installing requirements for sd-webui-cloud-inference
Launching Web UI with arguments: --listen --enable-insecure-extension-access --share --disable-safe-unpickle --theme dark --no-hashing --xformers --multiple
2023-10-25 14:43:00.355931: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-10-25 14:43:00.355987: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-10-25 14:43:00.356026: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-10-25 14:43:02.412464: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
face_yolov8n.pt: 100% 6.21M/6.21M [00:00<00:00, 31.5MB/s]
face_yolov8s.pt: 100% 22.5M/22.5M [00:00<00:00, 119MB/s]
hand_yolov8n.pt: 100% 6.22M/6.22M [00:00<00:00, 213MB/s]
person_yolov8n-seg.pt: 100% 6.75M/6.75M [00:00<00:00, 230MB/s]
person_yolov8s-seg.pt: 100% 23.8M/23.8M [00:00<00:00, 214MB/s]
[-] ADetailer initialized. version: 23.10.1, num models: 9
2023-10-25 14:43:13,442 - ControlNet - INFO - ControlNet v1.1.411
ControlNet preprocessor location: /content/vorst-cavry/extensions/controlnet-s/annotator/downloads
2023-10-25 14:43:13,692 - ControlNet - INFO - ControlNet v1.1.411
Loading weights [None] from /content/vorst-cavry/models/Stable-diffusion/Cavry_V2.safetensors
Creating model from config: /content/vorst-cavry/configs/v1-inference.yaml
(…)it-large-patch14/resolve/main/vocab.json: 100% 961k/961k [00:00<00:00, 3.90MB/s]
(…)it-large-patch14/resolve/main/merges.txt: 100% 525k/525k [00:00<00:00, 2.86MB/s]
(…)h14/resolve/main/special_tokens_map.json: 100% 389/389 [00:00<00:00, 2.23MB/s]
(…)tch14/resolve/main/tokenizer_config.json: 100% 905/905 [00:00<00:00, 4.70MB/s]
(…)t-large-patch14/resolve/main/config.json: 100% 4.52k/4.52k [00:00<00:00, 20.6MB/s]
Model loaded in 12.1s (load weights from disk: 1.7s, create model: 2.1s, apply weights to model: 7.4s, apply half(): 0.1s, load textual inversion embeddings: 0.2s, calculate empty prompt: 0.5s).
[cloud-inference] reloading modules.img2img
[cloud-inference] reloading modules.api.api
[cloud-inference] reloading img2imgalt.py - processing
[cloud-inference] reloading loopback.py - processing
[cloud-inference] reloading outpainting_mk_2.py - process_images
[cloud-inference] reloading poor_mans_outpainting.py - process_images
[cloud-inference] reloading prompt_matrix.py - process_images
[cloud-inference] reloading prompts_from_file.py - process_images
[cloud-inference] reloading run_n_times.py - process_images
[cloud-inference] reloading sd_upscale.py - processing
[cloud-inference] reloading xyz_grid.py - process_images
[cloud-inference] reloading xyz_grid.py - processing
[cloud-inference] reloading !adetailer.py - process_images
[cloud-inference] reloading lora_block_weight.py - process_images
[cloud-inference] reloading controlnet.py - processing
[cloud-inference] reloading movie2movie.py - process_images
[cloud-inference] reloading rps.py - process_images
[cloud-inference] hijack modules.processing.process_images, old: <modules.processing.process_images>, new: <scripts.hijack._hijack_process_images>
[cloud-inference] hijack modules.postprocessing.run_postprocessing, old: <modules.postprocessing.run_postprocessing>, new: <scripts.hijack._hijack_run_postprocessing>
[cloud-inference] hijack xyz_grid
[cloud-inference] refreshing models...
Loading extension: sd-webui-cloud-inference
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
== WD14 tagger /gpu:0, uname_result(system='Linux', node='ea192211d168', release='5.15.120+', version='#1 SMP Wed Aug 30 11:19:59 UTC 2023', machine='x86_64') ==
all detected, remote.moe trying to connect...
Warning: Permanently added 'localhost.run' (RSA) to the list of known hosts.
all detected, cloudflared trying to connect...
Download cloudflared...: 100% 34.8M/34.8M [00:00<00:00, 307MB/s]
Applying attention optimization: xformers... done.
Init / preset error.
Public WebUI Colab URL: None 
Public WebUI Colab URL: https://b03c8b2b-c6a3-4a78.gradio.live/ 
Public WebUI Colab URL: https://28af48ff804191.lhr.life/
Please do not use this link we are getting ERROR: Exception in ASGI application:  https://c2bcc59914550d753c.gradio.live/
Public WebUI Colab URL: https://annex-negative-applies-deadline.trycloudflare.com/
[cloud-inference] hijack failed: extensions.sd-webui-controlnet.scripts.global_state.update_cn_models
*** Error executing callback app_started_callback for /content/vorst-cavry/extensions/sd-webui-cloud-inference/scripts/main_ui.py
    Traceback (most recent call last):
      File "/content/vorst-cavry/modules/script_callbacks.py", line 139, in app_started_callback
        c.callback(demo, app)
      File "/content/vorst-cavry/extensions/sd-webui-cloud-inference/scripts/hijack.py", line 58, in hijack_on_app_started
        self._hijack_update_cn_models() # update once
      File "/content/vorst-cavry/extensions/sd-webui-cloud-inference/scripts/hijack.py", line 130, in _hijack_update_cn_models
        self.hijack_map['extensions.sd-webui-controlnet.scripts.global_state.update_cn_models']['old']()
    KeyError: 'extensions.sd-webui-controlnet.scripts.global_state.update_cn_models'

---`

**Comment by vorstcavry** [comment]
> @vorstcavry, could you please provide additional logs? It's possible that some extensions are causing the issue to not work.

I have found several extensions that can make the performance of the sd-webui-inference extension become an error, it's a pity that the extension that makes it error is an extension that I often use

**Comment by AnyISalIn** [comment]
> > @vorstcavry, could you please provide additional logs? It's possible that some extensions are causing the issue to not work.
> 
> I have found several extensions that can make the performance of the sd-webui-inference extension become an error, it's a pity that the extension that makes it error is an extension that I often use

Hi, could you provide a list of the extensions so that maybe I can help fix them?
